### ISSUE TITLE
mj_envs dependency deprecated

### ISSUE THREAD

**Issue by ismarou** [GT-STAR-Lab/KODex#1]
Hi,

This work is very nice, thank you for open-sourcing the code.

As I am trying to install the dependencies, I have the following question:

mj_envs has been replaced by robohive, where it has been suggested that in order to get the mj_envs dependency someone needs to clone the previous stable branch.

However, the installation of the dependency seems to be breaking with post-Deepmind bindings.

So, I would like you to ask which branch of the mj_envs/robohive did you install in order to make this project work and if there is anything special about that you had to do in order to make it work.

Best,
Isidoros

**Comment by y8han** [comment]
Hi,
Thank you for your interest in our work! I was not aware that they updated the environment files after a few years. orz
I just compared my local files with their branch histories, and I think [hand-vil](https://github.com/vikashplus/robohive/tree/hand-vil) should be the branch that we used for this project.
Please let me know if it works and then I will update the README.

**Comment by ismarou** [comment]
Hello, thanks for your response!

However, the problem remains the same. Can you add the requirements.txt of your virtual env to the project?

Best,
Isidoros

**Comment by y8han** [comment]
Hi Isidoros,
I just attached the mj_envs file we used before as a zip file. Please unzip it and put it under the same folder as mjrl. Then, you could try to install mj_envs following the README file. Let me know if it works!

[mj_envs.zip](https://github.com/GT-STAR-Lab/KODex/files/13430680/mj_envs.zip)

**Comment by ismarou** [comment]
Hey Yunhai,

Thanks for the .zip. No, the errors remain the same as with the stable version of robohive.

I am attaching the error messages in case that is of help:

Obtaining file:///home/ismarou/Downloads/mjrl/mj_envs
  Preparing metadata (setup.py) ... done
Collecting click
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting gym==0.13
  Using cached gym-0.13.0-py3-none-any.whl
Collecting mujoco-py<2.1,>=2.0
  Using cached mujoco-py-2.0.2.13.tar.gz (792 kB)
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for mujoco-py<2.1,>=2.0 from https://files.pythonhosted.org/packages/2f/48/b108057c1a23c8da9f4cdc7a7c46ab7cec49c3563c0706d50f2527de6ba0/mujoco-py-2.0.2.13.tar.gz (from mj-envs==1.0.0).
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: termcolor in /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from mj-envs==1.0.0) (2.1.0)
Requirement already satisfied: six in /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from gym==0.13->mj-envs==1.0.0) (1.16.0)
Collecting cloudpickle~=1.2.0
  Using cached cloudpickle-1.2.2-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: numpy>=1.10.4 in /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from gym==0.13->mj-envs==1.0.0) (1.19.2)
Collecting pyglet>=1.2.0
  Using cached pyglet-2.0.10-py3-none-any.whl (858 kB)
Collecting scipy
  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
Requirement already satisfied: glfw>=1.4.0 in /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from mujoco-py<2.1,>=2.0->mj-envs==1.0.0) (2.6.3)
Requirement already satisfied: imageio>=2.1.2 in /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from mujoco-py<2.1,>=2.0->mj-envs==1.0.0) (2.31.2)
Requirement already satisfied: Cython>=0.27.2 in /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from mujoco-py<2.1,>=2.0->mj-envs==1.0.0) (0.29.36)
Requirement already satisfied: fasteners~=0.15 in /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from mujoco-py<2.1,>=2.0->mj-envs==1.0.0) (0.19)
Requirement already satisfied: cffi>=1.10 in /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from mujoco-py<2.1,>=2.0->mj-envs==1.0.0) (1.15.1)
Collecting importlib-metadata
  Using cached importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
Requirement already satisfied: pycparser in /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from cffi>=1.10->mujoco-py<2.1,>=2.0->mj-envs==1.0.0) (2.21)
Requirement already satisfied: pillow>=8.3.2 in /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from imageio>=2.1.2->mujoco-py<2.1,>=2.0->mj-envs==1.0.0) (9.4.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from importlib-metadata->click->mj-envs==1.0.0) (4.4.0)
Collecting zipp>=0.5
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for mujoco-py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      running bdist_wheel
      running build
      performance hint: mujoco_py/cymj.pyx:67:5: Exception check on 'c_warning_callback' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: mujoco_py/cymj.pyx:104:5: Exception check on 'c_error_callback' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          See c_warning_callback, which is the C wrapper to the user defined function
          '''
          global py_warning_callback
          global mju_user_warning
          py_warning_callback = warn
          mju_user_warning = c_warning_callback
                             ^
      ------------------------------------------------------------
      
      mujoco_py/cymj.pyx:92:23: Cannot assign type 'void (const char *) except * nogil' to 'void (*)(const char *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (const char *) except * nogil'.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          See c_warning_callback, which is the C wrapper to the user defined function
          '''
          global py_error_callback
          global mju_user_error
          py_error_callback = err_callback
          mju_user_error = c_error_callback
                           ^
      ------------------------------------------------------------
      
      mujoco_py/cymj.pyx:127:21: Cannot assign type 'void (const char *) except * nogil' to 'void (*)(const char *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (const char *) except * nogil'.
      Removing old mujoco_py cext /tmp/pip-install-ix2zg0uc/mujoco-py_14365d22b24143d9a1d777d75d23e48a/mujoco_py/generated/cymj_2.0.2.13_37_linuxcpuextensionbuilder_37.so
      Compiling /tmp/pip-install-ix2zg0uc/mujoco-py_14365d22b24143d9a1d777d75d23e48a/mujoco_py/cymj.pyx because it changed.
      [1/1] Cythonizing /tmp/pip-install-ix2zg0uc/mujoco-py_14365d22b24143d9a1d777d75d23e48a/mujoco_py/cymj.pyx
      Traceback (most recent call last):
        File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 250, in build_wheel
          metadata_directory)
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 417, in build_wheel
          wheel_directory, config_settings)
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 51, in <module>
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-7l09w8y8/normal/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 369, in run
          self.run_command("build")
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 29, in run
        File "/tmp/pip-install-ix2zg0uc/mujoco-py_14365d22b24143d9a1d777d75d23e48a/mujoco_py/__init__.py", line 3, in <module>
          from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
        File "/tmp/pip-install-ix2zg0uc/mujoco-py_14365d22b24143d9a1d777d75d23e48a/mujoco_py/builder.py", line 510, in <module>
          cymj = load_cython_ext(mujoco_path)
        File "/tmp/pip-install-ix2zg0uc/mujoco-py_14365d22b24143d9a1d777d75d23e48a/mujoco_py/builder.py", line 105, in load_cython_ext
          cext_so_path = builder.build()
        File "/tmp/pip-install-ix2zg0uc/mujoco-py_14365d22b24143d9a1d777d75d23e48a/mujoco_py/builder.py", line 221, in build
          built_so_file_path = self._build_impl()
        File "/tmp/pip-install-ix2zg0uc/mujoco-py_14365d22b24143d9a1d777d75d23e48a/mujoco_py/builder.py", line 273, in _build_impl
          so_file_path = super()._build_impl()
        File "/tmp/pip-install-ix2zg0uc/mujoco-py_14365d22b24143d9a1d777d75d23e48a/mujoco_py/builder.py", line 234, in _build_impl
          dist.ext_modules = cythonize([self.extension])
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-7l09w8y8/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: /tmp/pip-install-ix2zg0uc/mujoco-py_14365d22b24143d9a1d777d75d23e48a/mujoco_py/cymj.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mujoco-py
Failed to build mujoco-py
ERROR: Could not build wheels for mujoco-py, which is required to install pyproject.toml-based projects

Can you zip your environment in a requirements.txt and possible upload that? I think this will be the closest imitation of your environment.

Best,
Isidoros

**Comment by y8han** [comment]
Oh, I know how to solve this error and it is purely caused by the mujoco_py installation as I have seen it twice when I installed the same KODex env on another local machine in our lab.
First, download Mujoco210 and include the path into _~/.bashrc_.
```  
cd ~/Downloads/
wget https://github.com/deepmind/mujoco/releases/download/2.1.0/mujoco210-linux-x86_64.tar.gz
mv mujoco210-linux-x86_64.tar.gz mujoco210
tar -zxvf mujoco210-linux-x86_64.tar.gz
mkdir ~/mujoco
cp -r mujoco210 ~/mujoco
sudo gedit ~/.bashrc
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.mujoco/mujoco210/bin
export MUJOCO_KEY_PATH=~/.mujoco${MUJOCO_KEY_PATH}
source ~/.bashrc
```
There are more than one ways to download the file, so just make sure it is moved to _~/.mujoco_ with the key and include the path to _~/.bashrc_. Then
```
conda activate mjrl-env
pip3 install mujoco_py
```
You will then probably see the same error, either in the installation process, or after commanding `import mujoco_py` under a python environment. This is probably caused by the mismatched version of `Cython` module. To solve this, simply install another version of it
```
pip3 install Cython==3.0.0a10
```
After this, you should be able to install mujoco_py and successfully import it. And you should also be able to install any other missing modules.
Let me know if it helps.

**Comment by y8han** [comment]
One additional note: make sure to download the same version of Mujoco2x0 with the version of mujoco_py after you run `pip3 install mujoco_py`.

**Comment by ismarou** [comment]
Hi Yunhai,

Thanks for the help. Your advice indeed helped me install mj_envs. However, your code is still not running.

The new error is:

(mjrl-env) ismarou@ismarou-Legion-5-15ACH6H:~/Downloads/KODex2/KODex/Door$ MJPL /home/ismarou/anaconda3/envs/mjrl-env/bin/python Koopman_training.py --env_name door-v0 --demo_file ./Data/Testing.pickle --num_demo 0 --koopmanoption Drafted --velocity False --save_matrix True --matrix_file ./Results/KODex/koopmanMatrix.npy --control True --error_type demo --visualize True --unseen_test False --rl_policy ./Results/Expert_policy/best_policy.pickle
Import error. Trying to rebuild mujoco_py.
Traceback (most recent call last):
  File "/home/ismarou/Downloads/mjrl/mjrl/envs/mujoco_env.py", line 12, in <module>
    import mujoco_py
  File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/mujoco_py/__init__.py", line 2, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/mujoco_py/builder.py", line 504, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/mujoco_py/builder.py", line 111, in load_cython_ext
    mod = load_dynamic_ext('cymj', cext_so_path)
  File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/mujoco_py/builder.py", line 130, in load_dynamic_ext
    return loader.load_module()
ImportError: /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/torch/lib/../../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-15.so.1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Koopman_training.py", line 5, in <module>
    import mj_envs
  File "/home/ismarou/Downloads/mjrl/mj_envs/mj_envs/__init__.py", line 1, in <module>
    import  mj_envs.hand_manipulation_suite 
  File "/home/ismarou/Downloads/mjrl/mj_envs/mj_envs/hand_manipulation_suite/__init__.py", line 2, in <module>
    from mjrl.envs.mujoco_env import MujocoEnv
  File "/home/ismarou/Downloads/mjrl/mjrl/__init__.py", line 1, in <module>
    import mjrl.envs
  File "/home/ismarou/Downloads/mjrl/mjrl/envs/__init__.py", line 31, in <module>
    from mjrl.envs.mujoco_env import MujocoEnv
  File "/home/ismarou/Downloads/mjrl/mjrl/envs/mujoco_env.py", line 15, in <module>
    raise error.DependencyNotInstalled("{}. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)".format(e))
gym.error.DependencyNotInstalled: /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/torch/lib/../../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-15.so.1). (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)


Have you encountered this before?

Best,
Isidoros

P.S. Ofc, I tried sudo apt-get install libglfw-dev, but it did not change the error.

**Comment by y8han** [comment]
Hi,
I guess its still caused by the unsuccessful installation of _mujoco_py_, so I am wondering if you are able to import this library directly using interactive Python command line?

**Comment by ismarou** [comment]
You are right, I get a problem when I call mujoco_py, but my installation sequence went exactly as you describe above:

(base) ismarou@ismarou-Legion-5-15ACH6H:~$ conda activate mjrl-env
(mjrl-env) ismarou@ismarou-Legion-5-15ACH6H:~$ whereis python
python: /home/ismarou/anaconda3/envs/mjrl-env/bin/python
(mjrl-env) ismarou@ismarou-Legion-5-15ACH6H:~$ /home/ismarou/anaconda3/envs/mjrl-env/bin/python -m pip install mujoco_py
Requirement already satisfied: mujoco_py in ./anaconda3/envs/mjrl-env/lib/python3.7/site-packages (2.1.2.14)
Requirement already satisfied: numpy>=1.11 in ./anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from mujoco_py) (1.19.2)
Requirement already satisfied: fasteners~=0.15 in ./anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from mujoco_py) (0.19)
Requirement already satisfied: Cython>=0.27.2 in ./anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from mujoco_py) (3.0.0a10)
Requirement already satisfied: glfw>=1.4.0 in ./anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from mujoco_py) (2.6.3)
Requirement already satisfied: cffi>=1.10 in ./anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from mujoco_py) (1.15.1)
Requirement already satisfied: imageio>=2.1.2 in ./anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from mujoco_py) (2.31.2)
Requirement already satisfied: pycparser in ./anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from cffi>=1.10->mujoco_py) (2.21)
Requirement already satisfied: pillow>=8.3.2 in ./anaconda3/envs/mjrl-env/lib/python3.7/site-packages (from imageio>=2.1.2->mujoco_py) (9.4.0)
(mjrl-env) ismarou@ismarou-Legion-5-15ACH6H:~$ cd .mujoco
(mjrl-env) ismarou@ismarou-Legion-5-15ACH6H:~/.mujoco$ ls
mjkey.txt  mujoco210
(mjrl-env) ismarou@ismarou-Legion-5-15ACH6H:~/.mujoco$ 

and the .bashrc contains:

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ismarou/.mujoco/mujoco210/bin
export MUJOCO_KEY_PATH=~/.mujoco${MUJOCO_KEY_PATH}

**Comment by y8han** [comment]
Hi, that's a bit weird. Because from my experiences, the first time we called _mujoco_py_, we got some warning messages, but the second time, it worked perfectly. The Mujoco_py I am using is '2.0.2.8', so you might try to install the exactly same version, following the previous instructions.

**Comment by ismarou** [comment]
But, you told me to install mujoco210. Doesn't that mean that I should also have some mujco 2.1.X.X variation?

**Comment by ismarou** [comment]
Successfully installed mujoco_py-2.0.2.8
(mjrl-env) ismarou@ismarou-Legion-5-15ACH6H:~/Downloads/KODex2/KODex$ /home/ismarou/anaconda3/envs/mjrl-env/bin/python
Python 3.7.16 (default, Jan 17 2023, 22:20:44) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mujoco_py

You appear to be missing MuJoCo.  We expected to find the file here: /home/ismarou/.mujoco/mujoco200

This package only provides python bindings, the library must be installed separately.

Please follow the instructions on the README to install MuJoCo

    https://github.com/openai/mujoco-py#install-mujoco

Which can be downloaded from the website

    https://www.roboti.us/index.html

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/mujoco_py/builder.py", line 505, in <module>
    mujoco_path, key_path = discover_mujoco()
  File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/mujoco_py/utils.py", line 93, in discover_mujoco
    raise Exception(message)
Exception: 
You appear to be missing MuJoCo.  We expected to find the file here: /home/ismarou/.mujoco/mujoco200

This package only provides python bindings, the library must be installed separately.

Please follow the instructions on the README to install MuJoCo

    https://github.com/openai/mujoco-py#install-mujoco

Which can be downloaded from the website

    https://www.roboti.us/index.html

With the mujoco_py variation you said, we get the following error.

Could you please upload the full requirements.txt of your dependencies to be on the same page?

Best,
Isidoros

**Comment by y8han** [comment]
Sorry for the confusion. I used several different versions of Mujoco lib for different projects, so I was somehow under the wrong conda env. 
However, the good news is that I indeed saw this error message you posted! I think all you need to do is to make sure you have Mujoco200 under ~/.mujoco (also, add the new path in ~/.bashrc.) and then test again if you could import mujoco_py.
For your convenient, I have attached the file. 
[mujoco200.zip](https://github.com/GT-STAR-Lab/KODex/files/13541452/mujoco200.zip)

**Comment by ismarou** [comment]
I did it with mujoco200. I could import it,  but the GLIBCXX_3.4.30 error persists:

Traceback (most recent call last):
  File "/home/ismarou/Downloads/mjrl/mjrl/envs/mujoco_env.py", line 12, in <module>
    import mujoco_py
  File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/mujoco_py/builder.py", line 506, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/mujoco_py/builder.py", line 106, in load_cython_ext
    mod = load_dynamic_ext('cymj', cext_so_path)
  File "/home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/mujoco_py/builder.py", line 125, in load_dynamic_ext
    return loader.load_module()
ImportError: /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/torch/lib/../../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-15.so.1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Koopman_training.py", line 5, in <module>
    import mj_envs
  File "/home/ismarou/Downloads/mjrl/mj_envs/mj_envs/__init__.py", line 1, in <module>
    import  mj_envs.hand_manipulation_suite 
  File "/home/ismarou/Downloads/mjrl/mj_envs/mj_envs/hand_manipulation_suite/__init__.py", line 2, in <module>
    from mjrl.envs.mujoco_env import MujocoEnv
  File "/home/ismarou/Downloads/mjrl/mjrl/__init__.py", line 1, in <module>
    import mjrl.envs
  File "/home/ismarou/Downloads/mjrl/mjrl/envs/__init__.py", line 31, in <module>
    from mjrl.envs.mujoco_env import MujocoEnv
  File "/home/ismarou/Downloads/mjrl/mjrl/envs/mujoco_env.py", line 15, in <module>
    raise error.DependencyNotInstalled("{}. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)".format(e))
gym.error.DependencyNotInstalled: /home/ismarou/anaconda3/envs/mjrl-env/lib/python3.7/site-packages/torch/lib/../../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-15.so.1). (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)

**Comment by y8han** [comment]
Ok, I will share the full requirements.txt of my dependencies. Also, I was only testing the KODex codes on Ubuntu 20.04 and Ubuntu 22.04. 

> name: mjrl-env
> channels:
>   - pytorch
>   - nvidia
>   - defaults
> dependencies:
>   - _libgcc_mutex=0.1=main
>   - _openmp_mutex=5.1=1_gnu
>   - _pytorch_select=0.2=gpu_0
>   - backcall=0.2.0=pyhd3eb1b0_0
>   - ca-certificates=2023.08.22=h06a4308_0
>   - certifi=2022.12.7=py37h06a4308_0
>   - cuda-cudart=12.1.105=0
>   - cuda-cupti=12.1.105=0
>   - cuda-libraries=12.1.0=0
>   - cuda-nvrtc=12.1.105=0
>   - cuda-nvtx=12.1.105=0
>   - cuda-opencl=12.3.101=0
>   - cuda-runtime=12.1.0=0
>   - cudatoolkit=10.1.243=h6bb024c_0
>   - cudnn=7.6.5=cuda10.1_0
>   - decorator=5.1.1=pyhd3eb1b0_0
>   - intel-openmp=2023.1.0=hdb19cb5_46306
>   - ipython=7.31.1=py37h06a4308_1
>   - jedi=0.18.1=py37h06a4308_1
>   - ld_impl_linux-64=2.38=h1181459_1
>   - libcublas=12.1.0.26=0
>   - libcufft=11.0.2.4=0
>   - libcufile=1.8.1.2=0
>   - libcurand=10.3.4.101=0
>   - libcusolver=11.4.4.55=0
>   - libcusparse=12.0.2.55=0
>   - libffi=3.4.4=h6a678d5_0
>   - libgcc-ng=11.2.0=h1234567_1
>   - libgomp=11.2.0=h1234567_1
>   - libnpp=12.0.2.50=0
>   - libnvjitlink=12.1.105=0
>   - libnvjpeg=12.1.1.14=0
>   - libstdcxx-ng=11.2.0=h1234567_1
>   - matplotlib-inline=0.1.6=py37h06a4308_0
>   - mkl=2020.2=256
>   - mkl-service=2.3.0=py37he8ac12f_0
>   - ncurses=6.4=h6a678d5_0
>   - ninja=1.10.2=h06a4308_5
>   - ninja-base=1.10.2=hd09550d_5
>   - openssl=1.1.1w=h7f8727e_0
>   - parso=0.8.3=pyhd3eb1b0_0
>   - patchelf=0.17.2=h6a678d5_0
>   - pexpect=4.8.0=pyhd3eb1b0_3
>   - pickleshare=0.7.5=pyhd3eb1b0_1003
>   - pip=22.3.1=py37h06a4308_0
>   - prompt-toolkit=3.0.36=py37h06a4308_0
>   - ptyprocess=0.7.0=pyhd3eb1b0_2
>   - pygments=2.11.2=pyhd3eb1b0_0
>   - python=3.7.16=h7a1cb2a_0
>   - pytorch-cuda=12.1=ha16c6d3_5
>   - readline=8.2=h5eee18b_0
>   - setuptools=65.6.3=py37h06a4308_0
>   - six=1.16.0=pyhd3eb1b0_1
>   - sqlite=3.41.2=h5eee18b_0
>   - tabulate=0.8.10=py37h06a4308_0
>   - termcolor=2.1.0=py37h06a4308_0
>   - tk=8.6.12=h1ccaba5_0
>   - traitlets=5.7.1=py37h06a4308_0
>   - wcwidth=0.2.5=pyhd3eb1b0_0
>   - wheel=0.38.4=py37h06a4308_0
>   - xz=5.4.2=h5eee18b_0
>   - zlib=1.2.13=h5eee18b_0
>   - pip:
>       - cffi==1.15.1
>       - charset-normalizer==3.3.2
>       - click==8.1.7
>       - cloudpickle==1.2.2
>       - cycler==0.11.0
>       - cython==3.0.0a10
>       - fasteners==0.19
>       - fonttools==4.38.0
>       - geometric-fabrics-torch==0.0.0
>       - glfw==2.6.3
>       - gym==0.13.0
>       - idna==3.4
>       - imageio==2.31.2
>       - importlib-metadata==6.7.0
>       - kiwisolver==1.4.5
>       - matplotlib==3.5.3
>       - mujoco-py==2.0.2.8
>       - numpy==1.21.6
>       - nvidia-cublas-cu11==11.10.3.66
>       - nvidia-cuda-nvrtc-cu11==11.7.99
>       - nvidia-cuda-runtime-cu11==11.7.99
>       - nvidia-cudnn-cu11==8.5.0.96
>       - packaging==23.2
>       - pillow==9.5.0
>       - pycparser==2.21
>       - pyglet==2.0.10
>       - pyparsing==3.1.1
>       - python-dateutil==2.8.2
>       - requests==2.31.0
>       - scipy==1.7.3
>       - torch==1.13.1
>       - torchaudio==0.13.1
>       - torchvision==0.14.1
>       - tqdm==4.66.1
>       - typing-extensions==4.7.1
>       - urllib3==2.0.7
>       - zipp==3.15.0

**Comment by y8han** [comment]
Someone has install KODex from scratch, and written down the guidance. I think it should work if you follow these instructions!
[install.txt](https://github.com/GT-STAR-Lab/KODex/files/13773248/install.txt)
